### ISSUE TITLE
TODO: UI General Functionality

### ISSUE THREAD

**Issue by bagyenda** [bagyenda/njiwa#16]
- [ ] Instance data:
 - [ ] SM-DP/SM-SR OID(s)
 - [ ] SM-DP/SM-SR certificates and keys
 - [ ] CRL management (add/update)
 - [ ] CI certificate
