### ISSUE TITLE
TODO: UI - SM-DP Web UI

### ISSUE THREAD

**Issue by bagyenda** [bagyenda/njiwa#20]
This interface is available when a user attached to an SM-SD logs on via the UI

- [ ] Query EIS by EID+SM-SR (identified by OID)
- [ ] Send SCP03 command via SM-SR
- [ ] Query SM-DP transactions
