### ISSUE TITLE
TODO: UI - MNO interface

### ISSUE THREAD

**Issue by bagyenda** [bagyenda/njiwa#22]
This UI is available to MNO users. Functionality includes:
- [ ] SM-SR: Update/Set notification URL to be called when initial network attach by ISD-P for the MNO alert is received by SM-SR
- [ ] SM-DP: Query EIS: With EID & SM-SR (identified by OID), query EIS for eUICC data
- [ ] SM-SR: Assign M2M SP permissions for a profile template.
- [ ] SM-DP: Define an unpersonalised profile template: 
     - Template name and other basic data (as per SimAlliance spec).
     - List of per-batch parameters: Params to be set for each batch for personalisation purposes. For each param, indicate  whether the param is randomly generated by the SM-DP, or is provided in the batch input data.
     - List of per-card parameters: Params to be generated by the system during personalisation. For each param, generation mechanism (random, custom). Some param types and generation method will be pre-defined (e.g. Ki, PIN1, etc.)
     - Load template from (enhanced) Sim Profile Mark-Up (UXP) file
     - Load template from ASN.1 DER file
     - Edit/update template in Web UI. Support for file tree view
     - Support param marker syntax in certain profile elements **[VAR_NAME]**
- [ ] SM-DP: Upload/manage batch input data for a profile template: ICCID range, IMSI range, optional MSISDN range,  etc.
- [ ] SM-DP: Order a personalised profile: Provide EID, MSISDN optional, select profile template + batch, create transaction (Create-ISDP -> ProfileDownload -> Activate Profile -> UpdateConnectivity Params)
- [ ] SM-DP: Update Connectivity Params using SCP-03
- [ ] SM-SR: Update Connectivity Params
- [ ] SM-DP/SM-SR: Update ISD-P state (enable, disable)
- [ ] Query transaction status.
- [ ] SM-DP: Send SCP03 command transaction (using ECKA keys created during ISD-P creation, if they were stored)
- [ ] SM-SR: Send generic OTA command transaction via ISD-P to MNOSD
